### ISSUE TITLE
Sonic Mania Plus features

### ISSUE THREAD

**Issue by BeyondTheHorizon** [Erik-JS/SonicMania-SaveEditor#1]
Could you possibly add the features included in Plus like Mighty, Ray and save editing for Encore Mode, please?

**Comment by Erik-JS** [comment]
Looking at my local code, I see that I started doing that about 7 months ago, but I didn't finish it. Only the [ASI plugin repo](https://github.com/Erik-JS/SonicMania-ASI) was updated for 1.04.

Currently, I don't have much free time right now due to some personal issues, but I'll see what I can do to finish this, shouldn't take too long as I already have an idea of what needs to be done.

**Comment by BeyondTheHorizon** [comment]
Okay, and thank you.

**Comment by Erik-JS** [comment]
Encore Mode save slots are like an expansion of Mania Mode slots. Inside the save file, Mania slots are 1 2 3 4 5 6 7 8, Encore's are 11 12 13. Pretty much all I have to do is add new functions for choosing characters for Encore Mode, as common data like score and zone can be read from an Encore slot as if it was a Mania slot.

ASI plugins were updated 2 days ago and I'll probably update this repo on this weekend.

**Comment by BeyondTheHorizon** [comment]
That would be a good present (it is my birthday this Sunday).

**Comment by Erik-JS** [comment]
It's done. Closing this issue now.

Happy birthday! 🎂 

BTW, my birthday is tomorrow. 😁
